version: '3.2'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    environment:
        - TZ=America/Indiana/Indianapolis    
    command:
    - "--config.file=/etc/prometheus/prometheus.yml"
    - "--storage.tsdb.path=/prometheus"
    - "--web.console.libraries=/usr/share/prometheus/console_libraries"
    - "--web.console.templates=/usr/share/prometheus/consoles"
    - "--web.enable-admin-api"
    - "--web.listen-address=:8080"
    user: root
    volumes:
    - ./prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - ./prometheus_data:/prometheus
    - "/etc/localtime:/etc/localtime:ro"
    - "/etc/timezone:/etc/timezone:ro"    
    networks:
        docker-network:
          aliases:
            - prometheus
    labels:
      - 'traefik.enable=true'

networks:
  docker-network:
    external: true
